#include "platform.h"
#include "xparameters.h"
#include "xaxidma.h"
#include "xaxidma_hw.h"
#include "xtrafgen.h"
#include "xil_cache.h"
#include "xil_printf.h"
#include "xil_types.h"
#include "xstatus.h"
#include "sleep.h"

#include <stdlib.h>
#include <string.h>

/* Device identifiers generated by the Vitis BSP. */
#if defined(XPAR_AXIDMA_0_DEVICE_ID)
#define DMA_DEVICE_ID XPAR_AXIDMA_0_DEVICE_ID
#elif defined(XPAR_AXI_DMA_0_DEVICE_ID)
#define DMA_DEVICE_ID XPAR_AXI_DMA_0_DEVICE_ID
#else
#error "AXI DMA device ID was not found in xparameters.h"
#endif

#if defined(XPAR_AXI_TRAFFIC_GEN_0_DEVICE_ID)
#define TRAFGEN_DEVICE_ID XPAR_AXI_TRAFFIC_GEN_0_DEVICE_ID
#elif defined(XPAR_TRAFGEN_0_DEVICE_ID)
#define TRAFGEN_DEVICE_ID XPAR_TRAFGEN_0_DEVICE_ID
#elif defined(XPAR_XTRAFGEN_0_DEVICE_ID)
#define TRAFGEN_DEVICE_ID XPAR_XTRAFGEN_0_DEVICE_ID
#else
#error "AXI Traffic Generator device ID was not found in xparameters.h"
#endif

/*
 * The AXI4-Stream Subset Converter generates TLAST every 128 transfers.
 * Two packets are captured so that 256 symbols are sent to the Viterbi core.
 * This is longer than the decoder's approximate 177-symbol latency.
 */
#define SYMBOLS_PER_PACKET       128U
#define PACKET_COUNT             2U
#define TOTAL_SYMBOLS            (SYMBOLS_PER_PACKET * PACKET_COUNT)

/* Encoder output: one byte per input bit; only bits [1:0] contain the pair. */
#define ENCODED_PACKET_BYTES     SYMBOLS_PER_PACKET
#define ENCODED_TOTAL_BYTES      TOTAL_SYMBOLS

/* Viterbi input: one 16-bit word per encoded pair. */
#define SOFT_INPUT_BYTES         (TOTAL_SYMBOLS * 2U)

#define DMA_TIMEOUT_US           1000000U
#define ILA_ARM_DELAY_SECONDS    5U

/* Standard deviation of the simulated AWGN channel. */
#define NOISE_STANDARD_DEVIATION 0.55f

static XAxiDma AxiDma;
static XTrafGen TrafGen;

/* The DMA has no Data Realignment Engine, so use aligned DDR buffers. */
static u8  EncodedData[ENCODED_TOTAL_BYTES] __attribute__((aligned(64)));
static u16 SoftInput[TOTAL_SYMBOLS]          __attribute__((aligned(64)));

static void PrintDmaStatus(void)
{
    u32 Mm2sStatus;
    u32 S2mmStatus;

    Mm2sStatus = XAxiDma_ReadReg(
        AxiDma.RegBase,
        XAXIDMA_TX_OFFSET + XAXIDMA_SR_OFFSET
    );

    S2mmStatus = XAxiDma_ReadReg(
        AxiDma.RegBase,
        XAXIDMA_RX_OFFSET + XAXIDMA_SR_OFFSET
    );

    xil_printf("MM2S status: 0x%08x\r\n", (unsigned int)Mm2sStatus);
    xil_printf("S2MM status: 0x%08x\r\n", (unsigned int)S2mmStatus);
}

static int InitializeDma(void)
{
    XAxiDma_Config *Config;
    int Status;

    Config = XAxiDma_LookupConfig(DMA_DEVICE_ID);
    if (Config == NULL) {
        xil_printf("ERROR: AXI DMA configuration was not found.\r\n");
        return XST_FAILURE;
    }

    Status = XAxiDma_CfgInitialize(&AxiDma, Config);
    if (Status != XST_SUCCESS) {
        xil_printf("ERROR: AXI DMA initialization failed.\r\n");
        return XST_FAILURE;
    }

    if (XAxiDma_HasSg(&AxiDma) != 0) {
        xil_printf("ERROR: AXI DMA must use Simple mode.\r\n");
        return XST_FAILURE;
    }

    /* This application uses polling instead of interrupts. */
    XAxiDma_IntrDisable(
        &AxiDma,
        XAXIDMA_IRQ_ALL_MASK,
        XAXIDMA_DMA_TO_DEVICE
    );

    XAxiDma_IntrDisable(
        &AxiDma,
        XAXIDMA_IRQ_ALL_MASK,
        XAXIDMA_DEVICE_TO_DMA
    );

    return XST_SUCCESS;
}

static int InitializeTrafficGenerator(void)
{
    XTrafGen_Config *Config;
    int Status;

    Config = XTrafGen_LookupConfig(TRAFGEN_DEVICE_ID);
    if (Config == NULL) {
        xil_printf("ERROR: AXI Traffic Generator configuration was not found.\r\n");
        return XST_FAILURE;
    }

    Status = XTrafGen_CfgInitialize(&TrafGen, Config, Config->BaseAddress);
    if (Status != XST_SUCCESS) {
        xil_printf("ERROR: AXI Traffic Generator initialization failed.\r\n");
        return XST_FAILURE;
    }

    if (TrafGen.OperatingMode != XTG_MODE_STREAMING) {
        xil_printf("ERROR: AXI Traffic Generator is not in Streaming mode.\r\n");
        return XST_FAILURE;
    }

    /*
     * The ATG length register stores transfers minus one. Therefore, 127
     * produces 128 transfers. Two transactions produce two 128-byte packets.
     */
    XTrafGen_ResetStreamingRandomLen(&TrafGen);
    XTrafGen_SetStreamingTransLen(&TrafGen, SYMBOLS_PER_PACKET - 1U);
    XTrafGen_SetStreamingTransCnt(&TrafGen, PACKET_COUNT);

    return XST_SUCCESS;
}

static int WaitForDmaChannel(int Direction)
{
    u32 Timeout = DMA_TIMEOUT_US;
    u32 StatusRegister;
    u32 StatusOffset;

    while (XAxiDma_Busy(&AxiDma, Direction) != 0) {
        if (Timeout == 0U) {
            xil_printf("ERROR: DMA transfer timed out.\r\n");
            PrintDmaStatus();
            return XST_FAILURE;
        }

        Timeout--;
        usleep(1U);
    }

    StatusOffset = (Direction == XAXIDMA_DMA_TO_DEVICE) ?
                   XAXIDMA_TX_OFFSET : XAXIDMA_RX_OFFSET;

    StatusRegister = XAxiDma_ReadReg(
        AxiDma.RegBase,
        StatusOffset + XAXIDMA_SR_OFFSET
    );

    if ((StatusRegister & XAXIDMA_ERR_ALL_MASK) != 0U) {
        xil_printf("ERROR: AXI DMA reported a transfer error.\r\n");
        PrintDmaStatus();
        return XST_FAILURE;
    }

    return XST_SUCCESS;
}

static int CaptureEncodedPackets(void)
{
    u32 Packet;
    int Status;

    memset(EncodedData, 0, sizeof(EncodedData));

    /* Clean dirty cache lines before the DMA writes into this memory. */
    Xil_DCacheFlushRange((UINTPTR)EncodedData, ENCODED_TOTAL_BYTES);

    for (Packet = 0U; Packet < PACKET_COUNT; Packet++) {
        UINTPTR Destination;

        Destination = (UINTPTR)&EncodedData[Packet * ENCODED_PACKET_BYTES];

        Status = XAxiDma_SimpleTransfer(
            &AxiDma,
            Destination,
            ENCODED_PACKET_BYTES,
            XAXIDMA_DEVICE_TO_DMA
        );

        if (Status != XST_SUCCESS) {
            xil_printf("ERROR: Could not start S2MM packet %d.\r\n",
                       (int)(Packet + 1U));
            PrintDmaStatus();
            return XST_FAILURE;
        }

        /* Start the ATG only after the first S2MM receive is ready. */
        if (Packet == 0U) {
            XTrafGen_StreamEnable(&TrafGen);
        }

        Status = WaitForDmaChannel(XAXIDMA_DEVICE_TO_DMA);
        if (Status != XST_SUCCESS) {
            return XST_FAILURE;
        }

        xil_printf("Captured encoder packet %d/%d.\r\n",
                   (int)(Packet + 1U),
                   (int)PACKET_COUNT);
    }

    /* Discard stale cache lines before the CPU reads the DMA result. */
    Xil_DCacheInvalidateRange((UINTPTR)EncodedData, ENCODED_TOTAL_BYTES);

    return XST_SUCCESS;
}

/*
 * Sum of 12 uniform random values minus 6 approximates a standard normal
 * random variable. This avoids requiring the math library on the Zynq CPU.
 */
static float ApproximateGaussianNoise(void)
{
    u32 Index;
    float Sum = 0.0f;

    for (Index = 0U; Index < 12U; Index++) {
        Sum += (float)rand() / (float)RAND_MAX;
    }

    return Sum - 6.0f;
}

/*
 * Convert one noisy BPSK sample to the Viterbi core's 3-bit
 * signed-magnitude format:
 *
 *   000 = weakest 0       011 = strongest 0
 *   100 = weakest 1       111 = strongest 1
 */
static u8 MakeSoftDecision(u8 EncodedBit)
{
    float Sample;
    float MagnitudeFloat;
    u32 Magnitude;
    u8 Sign;

    Sample = (EncodedBit != 0U) ? 1.0f : -1.0f;
    Sample += NOISE_STANDARD_DEVIATION * ApproximateGaussianNoise();

    Sign = (Sample >= 0.0f) ? 1U : 0U;
    MagnitudeFloat = (Sample >= 0.0f) ? Sample : -Sample;

    /* Scale confidence to 0..3 and saturate at the strongest level. */
    Magnitude = (u32)((MagnitudeFloat * 3.0f) + 0.5f);
    if (Magnitude > 3U) {
        Magnitude = 3U;
    }

    return (u8)((Sign << 2) | (u8)Magnitude);
}

static void BuildSoftDecisionBuffer(void)
{
    u32 Index;

    for (Index = 0U; Index < TOTAL_SYMBOLS; Index++) {
        u8 EncodedPair;
        u8 DataIn0;
        u8 DataIn1;

        EncodedPair = (u8)(EncodedData[Index] & 0x03U);

        DataIn0 = MakeSoftDecision((u8)(EncodedPair & 0x01U));
        DataIn1 = MakeSoftDecision((u8)((EncodedPair >> 1) & 0x01U));

        /*
         * The Viterbi rate-1/2 AXI input uses one byte per soft symbol:
         * bits [2:0] = DATA_IN0, bits [10:8] = DATA_IN1.
         * All padding bits remain zero.
         */
        SoftInput[Index] = (u16)DataIn0 | ((u16)DataIn1 << 8);
    }
}

static void PrintFirstSamples(void)
{
    u32 Index;

    xil_printf("\r\nFirst 8 encoder/soft-decision values:\r\n");
    xil_printf("Index  Encoded[1:0]  Viterbi word\r\n");

    for (Index = 0U; Index < 8U; Index++) {
        xil_printf("%d      0x%02x          0x%04x\r\n",
                   (int)Index,
                   (unsigned int)(EncodedData[Index] & 0x03U),
                   (unsigned int)SoftInput[Index]);
    }
}

static int SendSoftDataToViterbi(void)
{
    int Status;

    Xil_DCacheFlushRange((UINTPTR)SoftInput, SOFT_INPUT_BYTES);

    xil_printf("\r\nArm the ILA trigger now. Transmission starts in %d seconds.\r\n",
               (int)ILA_ARM_DELAY_SECONDS);
    usleep(ILA_ARM_DELAY_SECONDS * 1000000U);

    Status = XAxiDma_SimpleTransfer(
        &AxiDma,
        (UINTPTR)SoftInput,
        SOFT_INPUT_BYTES,
        XAXIDMA_DMA_TO_DEVICE
    );

    if (Status != XST_SUCCESS) {
        xil_printf("ERROR: Could not start the MM2S transfer.\r\n");
        PrintDmaStatus();
        return XST_FAILURE;
    }

    Status = WaitForDmaChannel(XAXIDMA_DMA_TO_DEVICE);
    if (Status != XST_SUCCESS) {
        return XST_FAILURE;
    }

    return XST_SUCCESS;
}

int main(void)
{
    int Status;
    int Result = XST_FAILURE;

    init_platform();

    xil_printf("\r\n");
    xil_printf("============================================\r\n");
    xil_printf(" PYNQ-Z2 Convolutional Communication System\r\n");
    xil_printf("============================================\r\n");

    Status = InitializeDma();
    if (Status != XST_SUCCESS) {
        goto Done;
    }

    Status = InitializeTrafficGenerator();
    if (Status != XST_SUCCESS) {
        goto Done;
    }

    Status = CaptureEncodedPackets();
    if (Status != XST_SUCCESS) {
        goto Done;
    }

    /* Fixed seed makes the demonstration repeatable. */
    srand(1U);
    BuildSoftDecisionBuffer();
    PrintFirstSamples();

    Status = SendSoftDataToViterbi();
    if (Status != XST_SUCCESS) {
        goto Done;
    }

    xil_printf("\r\nMM2S transfer completed successfully.\r\n");
    xil_printf("Inspect the ILA for Viterbi M_AXIS_DATA TVALID and TDATA.\r\n");
    xil_printf("SOFTWARE TEST COMPLETED\r\n");
    Result = XST_SUCCESS;

Done:
    if (Result != XST_SUCCESS) {
        xil_printf("\r\nSOFTWARE TEST FAILED\r\n");
    }

    cleanup_platform();
    return Result;
}
